name: formula_one_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - "assets/images/"
    - "assets/icons/"
